name: appwrite
version: 8.2.1
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-flutter
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  device_info_plus: ^8.0.0
  flutter_web_auth_2: ^2.0.2
  http: ^0.13.5
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  web_socket_channel: ^2.2.0
  universal_html: ^2.0.8
  connectivity_plus: ^2.3.9
  path: ^1.8.2
  sembast: ^3.3.1
  sembast_sqflite: ^2.0.1
  sqflite: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
