name: appwrite
version: 9.0.0
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-flutter
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  device_info_plus: ^8.1.0
  flutter_web_auth_2: ^2.0.4
  http: ^0.13.5
  package_info_plus: ^3.0.3
  path_provider: ^2.0.13
  web_socket_channel: ^2.3.0
  universal_html: ^2.0.9

dev_dependencies:
  path_provider_platform_interface: ^2.0.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
